dist: trusty

language: php

cache:
    directories:
        - $HOME/.cache/composer

matrix:
    # mark as finished before allow_failures are run
    fast_finish: true
    include:
        - php: 7.1
          env: CONFIG="phpunit.xml" COVERAGE="unit"
        - php: 7.1
          env: CONFIG="phpunit-integration-legacy.xml" COVERAGE="integration"
        - php: 7.2
          env: CONFIG="phpunit.xml" COVERAGE="unit"
        - php: 7.2
          env: CONFIG="phpunit-integration-legacy.xml" COVERAGE="integration"
        - php: 7.3
          env: CONFIG="phpunit.xml" COVERAGE="unit"
        - php: 7.3
          env: CONFIG="phpunit-integration-legacy.xml" COVERAGE="integration"

# test only master (+ pull requests)
branches:
    only:
        - master

before_script:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    # Read-only OAuth token to work around GitHub API rate limits
    - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

    - composer update --no-suggest --prefer-dist

# execute phpunit as the script command
script:
    - composer validate --strict
    - ./vendor/bin/phpunit -d memory_limit=-1 --colors -c $CONFIG --coverage-clover=coverage.xml

# disable mail notifications
notifications:
    email: false

# reduce depth (history) of git checkout
git:
    depth: 1

# send coverage to codecov.io
after_success:
    - bash <(curl -s https://codecov.io/bash) -F $COVERAGE
