dist: xenial

language: php

php:
  - 7.4snapshot

cache:
  directories:
    - $HOME/.cache/composer

env:
  - CONFIG="phpunit.xml" COVERAGE="unit"
  - CONFIG="phpunit-integration-legacy.xml" COVERAGE="integration"

matrix:
  fast_finish: true

branches:
  only:
    - dev
    - master
    - php74
    - /^\d.\d+-release$/

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Read-only OAuth token to work around GitHub API rate limits
  - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

  - composer update --no-suggest --prefer-dist

  - pecl install intl
  - sed -i '200 a dump($value);' vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Persistence/TransformationProcessor/PcreCompiler.php

script:
  # - composer validate --strict
  - if [ "$CONFIG" != "" ] ; then vendor/bin/phpunit -c $CONFIG --coverage-clover=coverage.xml --colors=always ; fi

notifications:
  email: false

git:
  depth: 1
