services:
    eztags.api.persistence_handler.tags.cache:
        parent: ezpublish.spi.persistence.cache.abstractInMemoryHandler
        class: Netgen\TagsBundle\Core\Persistence\Cache\TagsHandler
        arguments: ["@eztags.api.persistence_handler.tags.storage"]
