netgen_tags_admin_field_autocomplete:
    path: /autocomplete
    controller: eztags.admin.controller.field:autoCompleteAction
    methods: [GET]

netgen_tags_admin_access_add_tags:
    path: /access/add
    controller: eztags.admin.controller.access:canAddTagsAction
    methods: [GET]

netgen_tags_admin_field_children:
    path: /children
    controller: eztags.admin.controller.field:childrenAction
    methods: [GET]
