netgen_tags_admin_synonym_add_select:
    path: /add/{mainTagId}
    defaults:
        _controller: eztags.admin.controller.synonym:addSynonymSelectAction
        _method: [GET, POST]

netgen_tags_admin_synonym_add:
    path: /add/{mainTagId}/{languageCode}
    defaults:
        _controller: eztags.admin.controller.synonym:addSynonymAction
        _method: [GET, POST]
