_eztagsTag:
    path: /tags/id/{tagId}/{viewType}/{layout}
    defaults:
        _controller: eztags.controller.tag_view:viewAction
        viewType: full
        layout: true
    methods: [GET]
    requirements:
        tagId: \d+
