services:
    eztags.field_type.eztags:
        class: Netgen\TagsBundle\Core\FieldType\Tags\Type
        parent: ezpublish.fieldType
        # Field type services need to be public in eZ Platform
        public: true
        arguments:
            - "@eztags.api.service.tags"
            - "@ezpublish.config.resolver"
        tags:
            - { name: ezplatform.field_type, alias: eztags }

    eztags.field_type.eztags.external_storage:
        class: Netgen\TagsBundle\Core\FieldType\Tags\TagsStorage
        # External storage services need to be public in eZ Platform
        public: true
        arguments:
            - "@eztags.field_type.eztags.storage_gateway"
            - "@eztags.api.service.tags"
        tags:
            - { name: ezpublish.fieldType.externalStorageHandler, alias: eztags }

    eztags.field_type.eztags.indexable:
        class: Netgen\TagsBundle\Core\FieldType\Tags\SearchField
        tags:
            - { name: ezplatform.field_type.indexable, alias: eztags }

    eztags.field_type.eztags.form_mapper:
        class: Netgen\TagsBundle\Core\FieldType\Tags\FormMapper
        arguments:
            - "@ezpublish.config.resolver"
        tags:
            - { name: ezplatform.field_type.form_mapper.definition, fieldType: eztags }
            - { name: ezplatform.field_type.form_mapper.value, fieldType: eztags }
