services:
    eztags.role.limitation_type.tag:
        class: Netgen\TagsBundle\Core\Limitation\TagLimitationType
        arguments:
            - "@ezpublish.api.persistence_handler"
            - "@eztags.api.persistence_handler.tags"
        tags:
            - { name: ezpublish.limitationType, alias: Tag }
