services:
    eztags.api.service.tags:
        alias: eztags.signalslot.service.tags

    eztags.signalslot.service.tags:
        class: Netgen\TagsBundle\Core\SignalSlot\TagsService
        arguments:
            - "@eztags.api.service.tags.inner"
            - "@ezpublish.signalslot.signal_dispatcher"

    eztags.api.service.tags.inner:
        class: Netgen\TagsBundle\Core\Repository\TagsService
        arguments:
            - "@ezpublish.siteaccessaware.repository"
            - "@eztags.api.persistence_handler.tags"
            - "@ezpublish.spi.persistence.cache.contentLanguageHandler"
