services:
    eztags.param_converter.tag:
        class: Netgen\TagsBundle\ParamConverter\TagParamConverter
        arguments:
            - "@eztags.api.service.tags"
        tags:
            - { name: request.param_converter, priority: 0 }
