services:
    # Controllers

    eztags.rest.controller.tags:
        class: Netgen\TagsBundle\Core\REST\Controller\Tags
        parent: ezpublish_rest.controller.base
        public: true
        arguments:
            - "@eztags.api.service.tags"

    # Value object visitors

    eztags.rest.output.value_object_visitor.cached_value:
        class: Netgen\TagsBundle\Core\REST\Output\ValueObjectVisitor\CachedValue
        parent: ezpublish_rest.output.value_object_visitor.base
        arguments:
            - "@request_stack"
            - "@ezpublish.config.resolver"
            - "@fos_http_cache.http.symfony_response_tagger"
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Netgen\TagsBundle\Core\REST\Values\CachedValue }

    eztags.rest.output.value_object_visitor.rest_tag:
        class: Netgen\TagsBundle\Core\REST\Output\ValueObjectVisitor\RestTag
        parent: ezpublish_rest.output.value_object_visitor.base
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Netgen\TagsBundle\Core\REST\Values\RestTag }

    eztags.rest.output.value_object_visitor.tag_list:
        class: Netgen\TagsBundle\Core\REST\Output\ValueObjectVisitor\TagList
        parent: ezpublish_rest.output.value_object_visitor.base
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Netgen\TagsBundle\Core\REST\Values\TagList }

    # Reimplemented to allow for specifying custom href to content list in the output
    eztags.rest.output.value_object_visitor.content_list:
        class: Netgen\TagsBundle\Core\REST\Output\ValueObjectVisitor\ContentList
        parent: ezpublish_rest.output.value_object_visitor.base
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Netgen\TagsBundle\Core\REST\Values\ContentList }

    eztags.rest.output.value_object_visitor.created_tag:
        class: Netgen\TagsBundle\Core\REST\Output\ValueObjectVisitor\CreatedTag
        parent: ezpublish_rest.output.value_object_visitor.base
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Netgen\TagsBundle\Core\REST\Values\CreatedTag }

    # Input parsers

    eztags.rest.input.parser.tag_create:
        class: Netgen\TagsBundle\Core\REST\Input\Parser\TagCreate
        parent: ezpublish_rest.input.parser
        arguments:
            - "@eztags.api.service.tags"
            - "@ezpublish_rest.parser_tools"
        tags:
            - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.TagCreate }

    eztags.rest.input.parser.tag_synonym_create:
        class: Netgen\TagsBundle\Core\REST\Input\Parser\TagSynonymCreate
        parent: ezpublish_rest.input.parser
        arguments:
            - "@eztags.api.service.tags"
            - "@ezpublish_rest.parser_tools"
        tags:
            - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.TagSynonymCreate }

    eztags.rest.input.parser.tag_update:
        class: Netgen\TagsBundle\Core\REST\Input\Parser\TagUpdate
        parent: ezpublish_rest.input.parser
        arguments:
            - "@eztags.api.service.tags"
            - "@ezpublish_rest.parser_tools"
        tags:
            - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.TagUpdate }
